include: package:flutter_lints/flutter.yaml

analyzer:
  errors: 
    must_be_immutable: error
    must_call_super: error
    parameter_assignments: error
    sort_unnamed_constructors_first: ignore
    sort_pub_dependencies: ignore
    invalid_annotation_target: ignore
