name: repo_viewer
description: "Repo Viewer"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  http: ^1.2.1
  auto_route: ^7.9.0
  flutter_secure_storage: ^9.0.0
  dartz: ^0.10.1
  oauth2: ^2.0.2
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1 
  json_annotation: ^4.8.1
  webview_flutter: ^4.7.0
  flash: ^3.1.0
  material_design_icons_flutter: ^7.0.7296
  sembast: ^3.6.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
